---
title: "Homework 2"
author: aw3253
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(readxl)
```


## Importing data (Problem 0)

I am importing data for Problems 1-2.

```{r}

babies_df = 
  read_csv("data/popular_baby_names.csv") %>% 
  janitor::clean_names()

trash_df = 
  read_excel("data/trash_wheel.xlsx") %>% 
  janitor::clean_names()

```



# Problem 1

```{r}
trash_df = 
  read_excel("data/trash_wheel.xlsx", 
      sheet = "Mr. Trash Wheel",
      range = "A2:N535",
      col_names = TRUE) %>% 
  janitor::clean_names()
  round(pull(trash_df, sports_balls))
  
trash_df = drop_na(trash_df) 

skimr::skim(trash_df)

trash_df

```


### Precipitation Data Cleaning

```{r}
precip18_df = 
  read_excel("data/trash_wheel.xlsx", 
      sheet = "2018 Precipitation",
      range = "A2:B14") %>%
  mutate(year=2018)

precip18_df


precip19_df = 
  read_excel("data/trash_wheel.xlsx", 
      sheet = "2019 Precipitation",
      range = "A2:B14") %>%
  mutate(year=2019)

precip19_df

#Combining Datasets

allprecip_df = 
  full_join(precip18_df, precip19_df)
  as.character(pull(allprecip_df, Month))
  
allprecip_df

```

Both data sets had about 12 observations for each, 2 in total which shows the precipitation in inches each month for years 2018 and 2019. The total precipitation in 2018 was 70.33 inches. The median number of sports balls in a dumpster in 2019 is `r median(pull(trash_df, sports_balls))`


## Problem 2
